version: 2
jobs:
  build:
    docker:
      - image: abcum/circle-golang:latest
        environment:
          GOOGLE_APPLICATION_CREDENTIALS: /root/gcloud-service-key.json
    working_directory: /go/src/github.com/abcum/fibre
    steps:
      - checkout
      - run:
          name: Clean
          command: make clean
      - run:
          name: Tests
          command: make tests
